services:

  www-motd:
    image: nginx:stable
    volumes:
    - ./service-motd/pages:/usr/share/nginx/html
    - ./service-motd/default.conf:/etc/nginx/conf.d/default.conf
    - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: "true"
      traefik.http.services.www-motd.loadbalancer.server.port: 80
      traefik.http.routers.www-motd.entrypoints: http
      traefik.http.routers.www-motd.rule: HostRegexp(`www.127.0.0.1.nip.io`)
      traefik.http.routers.www-motd.priority: 90

  www:
    labels:
      traefik.http.routers.www.rule: HostRegexp(`www.127.0.0.1.nip.io`) && HeadersRegexp(`Cookie`, `motd-read=true`)
      traefik.http.routers.www.priority: 100
