version: "3.7"

services:

  traefik:
    image: traefik:v2.4
    command:
    - --log=true
    - --log.level=DEBUG
    - --api.dashboard=true
    - --entrypoints.http.address=:80
    - --providers.docker=true
    - --providers.docker.exposedByDefault=false
    ports:
    - 127.0.0.1:80:80
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.rule: HostRegexp(`traefik.127.0.0.1.ip.go-nerd.de`)

  # Serves error pages
  # Test with non-existent host: curl -sv http://foo.127.0.0.1.ip.go-nerd.de
  error-pages:
    image: nginx:latest
    volumes:
    - ./error-pages/pages:/usr/share/nginx/error-pages
    - ./error-pages/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      traefik.enable: "true"
      traefik.http.services.error-pages-service.loadbalancer.server.port: 80
      traefik.http.routers.error-pages.entrypoints: http
      # (1) Catch-all rule
      traefik.http.routers.error-pages.rule: HostRegexp(`{host:.+}`)
      # (1) Lowest priority (served last)
      traefik.http.routers.error-pages.priority: 1
      traefik.http.routers.error-pages.middlewares: error-pages-middleware
      # (1) Catch-all custom 404 page
      traefik.http.middlewares.error-pages-middleware.errors.status: 404
      traefik.http.middlewares.error-pages-middleware.errors.service: error-pages-service
      traefik.http.middlewares.error-pages-middleware.errors.query: /404.html
      # (2) Error pages for internal service errors
      traefik.http.middlewares.outage-middleware.errors.status: 500-599
      traefik.http.middlewares.outage-middleware.errors.service: error-pages-service
      traefik.http.middlewares.outage-middleware.errors.query: /5xx.html

  # (4) Serves motto of the day (motd)
  # Test: curl --silent --verbose http://www.127.0.0.1.ip.go-nerd.de
  www-motd:
    image: nginx:stable
    volumes:
    - ./service-motd/pages:/usr/share/nginx/html
    - ./service-motd/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      traefik.enable: "true"
      traefik.http.services.www-motd.loadbalancer.server.port: 80
      traefik.http.routers.www-motd.entrypoints: http
      # (4) Same rule as service
      traefik.http.routers.www-motd.rule: HostRegexp(`www.127.0.0.1.ip.go-nerd.de`)
      # (4) Lower priority than service
      traefik.http.routers.www-motd.priority: 90

  # curl --silent --verbose --header "Cookie: maintenance-override=true" http://www.127.0.0.1.ip.go-nerd.de
  # curl --silent --verbose --header "Cookie: motd=true" http://www.127.0.0.1.ip.go-nerd.de
  www:
    image: nginx:stable
    volumes:
    - ./service:/usr/share/nginx/html
    labels:
      traefik.enable: "true"
      traefik.http.services.www.loadbalancer.server.port: 80
      traefik.http.routers.www.entrypoints: http
      # (1+2)
      #traefik.http.routers.www.rule: HostRegexp(`www.127.0.0.1.ip.go-nerd.de`)
      # (4) Show only if motd was already shown
      traefik.http.routers.www.rule: HostRegexp(`www.127.0.0.1.ip.go-nerd.de`) && HeadersRegexp(`Cookie`, `motd-read=true`)
      # (3) Show only if maintenance is overridden
      #traefik.http.routers.www.rule: HostRegexp(`www.127.0.0.1.ip.go-nerd.de`) && HeadersRegexp(`Cookie`, `maintenance-override=true`)
      # (1+4) Higher priority than catch-all and motd
      traefik.http.routers.www.priority: 100
      # (3) Use middleware defines earlier
      traefik.http.routers.www.middlewares: outage-middleware

  # (2) Helps to simulate server error
  # Test: curl -sv http://bin.127.0.0.1.ip.go-nerd.de/status/504
  httpbin:
    image: kennethreitz/httpbin
    labels:
      traefik.enable: "true"
      traefik.http.services.bin.loadbalancer.server.port: 80
      traefik.http.routers.bin.entrypoints: http
      traefik.http.routers.bin.rule: HostRegexp(`bin.127.0.0.1.ip.go-nerd.de`)
      # (1) Higher priority than catch-all
      traefik.http.routers.bin.priority: 100
      # (2) Use widdleware defined earlier
      traefik.http.routers.bin.middlewares: outage-middleware
