version: "3.7"

services:

  www-motd:
    image: nginx:stable
    volumes:
    - ./service-motd/pages:/usr/share/nginx/html
    - ./service-motd/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      traefik.enable: "true"
      traefik.http.services.www-motd.loadbalancer.server.port: 80
      traefik.http.routers.www-motd.entrypoints: http
      traefik.http.routers.www-motd.rule: HostRegexp(`www.localhost`)
      traefik.http.routers.www-motd.priority: 90

  www:
    labels:
      traefik.http.routers.www.rule: HostRegexp(`www.localhost`) && HeadersRegexp(`Cookie`, `motd-read=true`)
