version: "3.7"

services:

  error-pages:
    labels:
      traefik.http.middlewares.outage-middleware.errors.status: 500-599
      traefik.http.middlewares.outage-middleware.errors.service: error-pages-service
      traefik.http.middlewares.outage-middleware.errors.query: /5xx.html

  www:
    labels:
      traefik.http.routers.www.middlewares: outage-middleware

  httpbin:
    image: kennethreitz/httpbin
    labels:
      traefik.enable: "true"
      traefik.http.services.bin.loadbalancer.server.port: 80
      traefik.http.routers.bin.entrypoints: http
      traefik.http.routers.bin.rule: HostRegexp(`bin.localhost`)
      traefik.http.routers.bin.priority: 100
      traefik.http.routers.bin.middlewares: outage-middleware
