services:

  catch-all:
    image: nginx:latest
    volumes:
    - ./catch-all/pages:/usr/share/nginx/error-pages
    - ./catch-all/default.conf:/etc/nginx/conf.d/default.conf
    - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: "true"
      traefik.http.services.catch-all.loadbalancer.server.port: 80
      traefik.http.routers.catch-all.entrypoints: http
      traefik.http.routers.catch-all.rule: HostRegexp(`{host:.+}`)
      traefik.http.routers.catch-all.priority: 1
      traefik.http.middlewares.catch-all.errors.status: 404
      traefik.http.middlewares.catch-all.errors.service: catch-all
      traefik.http.middlewares.catch-all.errors.query: /404.html

  www:
    labels:
      traefik.http.routers.www.priority: 100
