services:

  traefik:
    image: traefik:v2.7
    command:
    - --log=true
    - --log.level=DEBUG
    - --api.dashboard=true
    - --entrypoints.http.address=:80
    - --providers.docker=true
    - --providers.docker.exposedByDefault=false
    ports:
    - 127.0.0.1:80:80
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.rule: HostRegexp(`traefik.127.0.0.1.nip.io`)
      traefik.http.routers.traefik.middlewares: error-pages-middleware

  

  pitschi:
    image: nginx:stable
    volumes:
    - ./pitschi/pages:/usr/share/nginx/error-pages
    - ./pitschi/default.conf:/etc/nginx/conf.d/default.conf
    - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.error-router.rule: HostRegexp(`{host:.+}`) 
      traefik.http.routers.error-router.priority: 1
      traefik.http.routers.error-router.entrypoints: http
      traefik.http.routers.error-router.middlewares: error-pages-middleware
      
      traefik.http.middlewares.error-pages-middleware.errors.status: 400-599
      traefik.http.middlewares.error-pages-middleware.errors.service: error-pages-service
      traefik.http.middlewares.error-pages-middleware.errors.query: /{status}.html
      
      traefik.http.services.error-pages-service.loadbalancer.server.port: 80
     

  www-motd:
    image: nginx:stable
    volumes:
    - ./www-motd/pages:/usr/share/nginx/html
    - ./www-motd/default.conf:/etc/nginx/conf.d/default.conf
    - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: "true"
      traefik.http.services.www-motd.loadbalancer.server.port: 80
      traefik.http.routers.www-motd.entrypoints: http
      traefik.http.routers.www-motd.rule: HostRegexp(`www.127.0.0.1.nip.io`)
      traefik.http.routers.www-motd.priority: 80

  www:
      image: nginx:stable
      volumes:
      - ./www/pages:/usr/share/nginx/html
      - ./www/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro
      labels:
        traefik.enable: "true"
        traefik.http.services.www.loadbalancer.server.port: 80
        traefik.http.routers.www.entrypoints: http
        traefik.http.routers.www.rule: HostRegexp(`www.127.0.0.1.nip.io`) && ( HeadersRegexp(`Cookie`, `motd-read=true`) || PathPrefix(`/api/`) )
        traefik.http.routers.www.priority: 100
        